name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean workspace
        run: |
          rm -rf ./* || true
          rm -rf ./.* || true

      - name: Initialize Next.js
        run: npx create-next-app@latest . --ts --tailwind --eslint --app --no-src-dir --import-alias "@/*" --use-npm --yes

      - name: Install additional dependencies
        run: |
          npm install framer-motion@10.16.4 lucide-react@0.294.0 --legacy-peer-deps

      - name: Update next.config
        run: |
          echo 'module.exports = {
            output: "export",
            images: {
              unoptimized: true,
            },
            basePath: "/NearForceWeb",
            assetPrefix: "/NearForceWeb/",
          }' > next.config.js

      - name: Create landing page
        run: |
          echo 'import { motion } from "framer-motion";
          
          export default function Page() {
            return (
              <div className="min-h-screen bg-white">
                <main className="container mx-auto px-4 py-16">
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                  >
                    <h1 className="text-5xl font-bold text-center mb-8">
                      Welcome to <span className="text-blue-600">NearForce</span>
                    </h1>
                    <p className="text-xl text-center text-gray-600">
                      Your trusted Salesforce consulting partner
                    </p>
                  </motion.div>
                </main>
              </div>
            );
          }' > app/page.tsx

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out