name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          npm install -g create-next-app@14.0.3
          npm install -g shadcn-ui@0.9.3
          npm ci

      - name: Initialize shadcn-ui
        run: |
          npx shadcn-ui@latest init --yes --skip-font
          npx shadcn-ui@latest add card --yes
          npx shadcn-ui@latest add button --yes
          npx shadcn-ui@latest add input --yes
          npx shadcn-ui@latest add textarea --yes

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out