name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Initialize Next.js
        run: |
          npx create-next-app@latest . --ts --tailwind --eslint --app --no-src-dir --import-alias "@/*" --use-npm --yes

      - name: Install additional dependencies
        run: |
          npm install framer-motion lucide-react
          npm install -D shadcn

      - name: Setup shadcn configuration
        run: |
          echo '{
            "$schema": "https://ui.shadcn.com/schema.json",
            "style": "default",
            "rsc": false,
            "tsx": true,
            "tailwind": {
              "config": "tailwind.config.ts",
              "css": "app/globals.css",
              "baseColor": "slate",
              "cssVariables": true
            },
            "aliases": {
              "components": "@/components",
              "utils": "@/lib/utils"
            }
          }' > components.json

      - name: Create utility functions
        run: |
          mkdir -p lib
          echo 'import { type ClassValue, clsx } from "clsx"
          import { twMerge } from "tailwind-merge"
          
          export function cn(...inputs: ClassValue[]) {
            return twMerge(clsx(inputs))
          }' > lib/utils.ts

      - name: Add UI components
        run: |
          npx shadcn@latest add button --yes
          npx shadcn@latest add card --yes
          npx shadcn@latest add input --yes
          npx shadcn@latest add textarea --yes

      - name: Update next.config
        run: |
          echo '/** @type {import("next").NextConfig} */
          const nextConfig = {
            output: "export",
            images: {
              unoptimized: true,
            },
            basePath: "/NearForceWeb",
            assetPrefix: "/NearForceWeb/",
          };
          
          module.exports = nextConfig;' > next.config.js

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out