name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install -D shadcn

      - name: Create directory structure and utils
        run: |
          mkdir -p components/ui/lib
          echo 'import { type ClassValue, clsx } from "clsx"
          import { twMerge } from "tailwind-merge"
          
          export function cn(...inputs: ClassValue[]) {
            return twMerge(clsx(inputs))
          }' > components/ui/lib/utils.ts

      - name: Initialize shadcn
        run: |
          npx shadcn@latest init --yes

      - name: Add UI components
        run: |
          npx shadcn@latest add button --yes
          npx shadcn@latest add card --yes
          npx shadcn@latest add input --yes
          npx shadcn@latest add textarea --yes

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out