name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install -g create-next-app@latest
          npm install -g shadcn-ui@latest

      - name: Setup shadcn-ui
        run: |
          npx shadcn-ui@latest init --yes --skip-font
          npx shadcn-ui@latest add card --yes
          npx shadcn-ui@latest add button --yes
          npx shadcn-ui@latest add input --yes
          npx shadcn-ui@latest add textarea --yes

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out