name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install
          npm install -D @shadcn/ui

      - name: Create directory structure and utils
        run: |
          mkdir -p components/ui/lib
          echo 'import { type ClassValue, clsx } from "clsx"
          import { twMerge } from "tailwind-merge"
          
          export function cn(...inputs: ClassValue[]) {
            return twMerge(clsx(inputs))
          }' > components/ui/lib/utils.ts

      - name: Add UI components
        run: |
          # Create components
          npx --yes shadcn-ui@latest add button
          npx --yes shadcn-ui@latest add card
          npx --yes shadcn-ui@latest add input
          npx --yes shadcn-ui@latest add textarea

      - name: Build
        run: |
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out